name: yosys
base: core20
version: '0.17'
summary: yosys FPGA logic synthesis
description: |
  Pre-packaged logic synthesis tool for use with open source FPGA toolchains
grade: devel
confinement: classic

build-packages:
  - build-essential
  - clang
  - bison
  - flex
  - cmake
  - git
  - libreadline-dev
  - gawk
  - tcl-dev
  - libffi-dev
  - pkg-config
  - python3
  - libboost-system-dev
  - libboost-python-dev
  - libboost-filesystem-dev
  - zlib1g-dev


parts:
  yosys:
    source: https://github.com/YosysHQ/yosys.git
    source-type: git
    source-depth: 1
    source-tag: yosys-0.17
    plugin: make
    make-parameters:
      - all
      - install
    override-build: |
      export PREFIX=/usr/
      make config-gcc
      snapcraftctl build
    stage-packages:
      - libtcl8.6
      - graphviz
      - xdot

apps:
  yosys:
    command: usr/local/bin/yosys 
